version: "3.7"
services:
  app:
    build:
      args:
        user: recp
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: equilibrados
    container_name: equilibrados-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - master

  nginx:
    image: nginx:alpine
    container_name: equilibrados-nginx
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - master

networks:
  master:
    driver: bridge